# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='website',
            new_name='encrypt',
        ),
    ]
