# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20161030_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='encrypt',
            field=models.CharField(max_length=50),
        ),
    ]
